### ISSUE TITLE
Page Not secure!

### ISSUE THREAD

**Issue by tabanammoc** [thewhiteh4t/seeker#382]
hi, I'm trying seeker and i see that when i send the ngrok link to my phone, google detect a dangerous site, and doesn't even let me get in... On my pc i don't had this problem, but the most useful thing is to catch the phone location for me... Does anyone know how to solve this problem? I tried to use bitly but it only change the visible link..
![ingannevole](https://user-images.githubusercontent.com/98542852/176994490-0e651972-9343-425e-ab74-de4211c55498.jpeg)
thats the interface.
i found this tool interesting anyway, but with this i cant really use it

**Comment by thewhiteh4t** [comment]
@tabanammoc this is most probably due to NGROK as many people use it for malicious activities. There are many other alternatives to ngrok which you can try, I just used it for example usage because its popular.

I found a similar issue here : https://stackoverflow.com/questions/72373457/deceptive-site-ahead-google-chrome-when-i-tried-to-open-the-ngrok-url

Closing this issue since its not really related to seeker.
