### ISSUE TITLE
Location Authorization

### ISSUE THREAD

**Issue by Sallysheridan** [thewhiteh4t/seeker#420]
Hi Friends, 
Is there any workaround or add that can avoid the user to see the Location permissions, 
Mostly people deny location and this kills the whole magic of Seeker. 
Location Allowance  should be like no matter if Deny or Allow Seeker should work .... Well ,, actually need a little help with this. 
Seeker is working beautiful  and reporting ,, but those dialog boxes for Loc Allowance.

**Comment by thewhiteh4t** [comment]
@Sallysheridan due to how browser security works this is currently not possible, you need some sort of browser exploit which can bypass the browser prompts for location permission but that is one part of the problem, next is your os level permissions.

That's why I built it as a social engineering technique.

**Comment by Sallysheridan** [comment]
Really appreciate your reply.. so there is a challenge there ..... I hope that soon you might make something  to workaround that little detail... the Seeker is a wonderful tool ... just need some polish ! 
Have a good one !

**Comment by thewhiteh4t** [comment]
@Sallysheridan thanks for your kind words, as soon as I come across a way to get around the permissions I will definitely implement it
