### ISSUE TITLE
"Externally managed" error

### ISSUE THREAD

**Issue by sharma1312** [thewhiteh4t/seeker#456]
**Describe the Error / Feature Request**

While typing the command ./seeker.sh or trying to execute the bash file, it is showing that this is externally managed, venv is not that nicely working for me,while using python3 seeker.py sometimes it is opening and some times traceback issue is encountering. While using pc to track location, the location is 4 hours far away. But it's ok as you said that using mobile can give us exact location. One more doubt, can't we track the location without asking their permission??

**Comment by thewhiteh4t** [comment]
@sharma1312 the externally managed error is coming from pip, this means that you need to install dependencies from your package manager manually, there are other workarounds also but it's better to simply install from package manager like apt etc

regarding permission, currently it is not possible to fetch it without asking for permissions because that is how browser and mobile security is designed to function
