### ISSUE TITLE
Links doesn't work on mobile

### ISSUE THREAD

**Issue by SlappySlap** [thewhiteh4t/seeker#72]
Hello,
i try your tool this morning and i see it doent work on my oneplus 6 (chrome) i just get blank page
and he btn continue not work 
[![Screenshot-20190604-084453.jpg](https://i.postimg.cc/wjDwFws4/Screenshot-20190604-084453.jpg)](https://postimg.cc/0z2Gydn7)

**Comment by thewhiteh4t** [comment]
That's because you did not pay attention and casually skipped `/` at the end
url that was provided : `https://explevi.serveo.net/nearyou/`
what you are visiting in the screenshot above : `https://explevi.serveo.net/nearyou`
Also, i have updated the script and now you can choose your subdomain,
example - 
`python3 seeker.py --subdomain google`
you will get a url like : `https://google.serveo.net/nearyou/`
