### ISSUE TITLE
Problem With Wan

### ISSUE THREAD

**Issue by Coderx430** [thewhiteh4t/seeker#87]
A Problem on wan:When i tested the tool on wan the tool showed that it got information from the other person
Like his browser info .e.t.c but it couldnt get Geo location info because the tool immediately says that the user denied permission for geolocation but my friend clearly accepted the geolocation button
maybe iam missing out something maybe a missing package which i need to install? Nevertheless Much Respect Sir keep up the good work!

**Comment by thewhiteh4t** [comment]
@Coderx430 Thank you for your kind words! and sorry for a delayed response, lot of stuff is going on,  you are not missing any package and your installation was fine, results in seeker depends from device to device and since I am not using google maps api for getting the location, such things are expected, i have few queries : 
1. Which phone?
2. which browser?
3. how many times did you try? 
4. is it showing permission denied every time on your friends phone?
5. is it working on your phone?
6. did your friend wait for the page to load completely before tapping on "continue" button?
7. is your friend NOT using high accuracy mode in his location settings?

**Comment by Coderx430** [comment]
Ok Now It seems that i have fixed my problem with the tool not giving me geolocation info but now i noticed that although i always get geolocation info from my friend's phone it seems that i always get different geolocation coordinates as if the target is moving from one point to another and sometimes it gives me the right coordinates by the way his android version is 9 maybe thats normal? since as you previously stated the tool doesnt use google maps api.Also we tested this using different browsers like chrome and firefox and they also both give different info on geolocation.

**Comment by thewhiteh4t** [comment]
@Coderx430 Great! If you remember there are calibration problems in almost all android sensors, and there are different ways to calibrate each, try to calibrate GPS sensor, if that does not work then I can't do much unfortunately as html geolocation api is very feature restricted, also android 9 completely fine, I have also tested on android 9 and i get approx 20m accuracy on OnePlus 3, reason I did not use google maps api is that it requires authenticated api, which creates problems in case of tools like seeker, both for me and the users, different browsers will act differently because inside they handle html api differently, some api work on firefox but others don't work on chrome or edge or safari, since they work on different engines

**Comment by Coderx430** [comment]
Ok sir thank you for clearing some confusions for me.So i suppose Like You said the problem is that each phone acts differently as well as each browser acts differently am i right? so that might be the case as to why i was getting different results each time i was running your tool also i noticed but i forgot to mention it that since i was getting different results (and i can say the difference in the distance was huge)  i told him to turn on his geolocation before he even clicks on my serveo link  and from that moment i saw that the tool began to grab the right coordinates.Anyway You did a very good job on that tool since Iam a programmer my self i know how difficult it can be to make even a simple but effective tool with minor bugs.Much respect!

**Comment by thewhiteh4t** [comment]
@Coderx430 Yes, you got it right, it depends upon hardware and browser both and this creates a variation of results and I know its highly experimental, and this was a good test to turn on location beforehand, this gave and advantage to seeker because otherwise it forces you to turn on the location after giving permission, I did try to add a delay when I was first creating it but results were same so I removed the delay when I released it and thank you for the appreciation! we learn from this community so I want to contribute to the community and this is one of my contributions.
